[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[rpc_endpoints]
conflux_testnet = "https://evmtestnet.confluxrpc.com"

[profile.conflux_testnet]
chain_id = 71
# You can add your deployer's private key in .env file
private_key = "${PRIVATE_KEY}"
